### ISSUE TITLE
TF0 transformation failed 

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sigmakee#44]
```
leme:workspace ar$ java -Xmx7g -classpath $SIGMA_CP com.articulate.sigma.trans.SUMOKBtoTFAKB
...
KB.termDepth(): no such term
Error in KB.mostSpecificTerm(): no such term:
Error in KB.mostSpecificTerm(): no such term:
Error in KB.mostSpecificTerm(): no such term:
Error in KB.mostSpecificTerm(): no such term:
Error in SUMOtoTFAform.modifyTypesToConstraints(): no constraint for RationalNumber
Error in SUMOKBtoTPTPKB.writeFile(): null
java.lang.NullPointerException
	at com.articulate.sigma.trans.SUMOtoTFAform.modifyTypesToConstraints(SUMOtoTFAform.java:1422)
	at com.articulate.sigma.trans.SUMOtoTFAform.process(SUMOtoTFAform.java:1223)
	at com.articulate.sigma.trans.SUMOtoTFAform.process(SUMOtoTFAform.java:1282)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:301)
	at com.articulate.sigma.trans.SUMOKBtoTFAKB.main(SUMOKBtoTFAKB.java:517)
```

The generation terminated with an exception. The version is the last commit in the master branch.

**Comment by apease** [comment]
I don't get this error with the latest Merge.kif loaded.  Which files were you processing?

**Comment by arademaker** [comment]
```
  <kb name="SUMO" >
    <constituent filename="Merge.kif" />
    <constituent filename="Mid-level-ontology.kif"/>
    <constituent filename="banana.kif"/>
  </kb>
```

The config.xml is in the `sumo/` and the `KBs` is a symlink to the `sumo/` path.

**Comment by apease** [comment]
could you send the contents of banana.kif ?

**Comment by apease** [comment]
no error on my side when using Merge + MILO

**Comment by apease** [comment]
banana.kif seems to trigger the error, although the TFF0 file is still produced, investigating further...

**Comment by apease** [comment]
not sure why banana.kif triggered this.  It was just a null during initialization that actually didn't appear to change the output.  In any case, I've trapped it and uploaded the fix

**Comment by arademaker** [comment]
OK, just registering that 0023bad6 solves this issue.
