### ISSUE TITLE
TF0 transformation errors and warnings

### ISSUE THREAD

**Issue by arademaker** [ontologyportal/sigmakee#47]
Using only Merge.kif, Mid-level-ontology.kif and banana.kif, I got the error below in the beginning of the TFO transformation:

```
Error in SUMOtoTFAform.matchingInstance(): null KB cache
formula: (<=>
  (and
    (equal
      (AbsoluteValueFn ?NUMBER1) ?NUMBER2) )
  (or
    (and
      (instance ?NUMBER1 NonnegativeRealNumber)
      (equal ?NUMBER1 ?NUMBER2))
    (and
      (instance ?NUMBER1 NegativeRealNumber)
      (equal ?NUMBER2
        (SubtractionFn 0 ?NUMBER1)))))
Error in SUMOKBtoTPTPKB.writeFile(): null
java.lang.NullPointerException
	at com.articulate.sigma.FormulaPreprocessor.computeVariableTypesRecurse(FormulaPreprocessor.java:700)
	at com.articulate.sigma.FormulaPreprocessor.computeVariableTypesRecurse(FormulaPreprocessor.java:684)
	at com.articulate.sigma.FormulaPreprocessor.computeVariableTypes(FormulaPreprocessor.java:668)
	at com.articulate.sigma.FormulaPreprocessor.findAllTypeRestrictions(FormulaPreprocessor.java:179)
	at com.articulate.sigma.trans.SUMOtoTFAform.process(SUMOtoTFAform.java:1234)
	at com.articulate.sigma.trans.SUMOtoTFAform.process(SUMOtoTFAform.java:1282)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:301)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:196)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:181)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:167)
	at com.articulate.sigma.trans.SUMOKBtoTPTPKB.writeFile(SUMOKBtoTPTPKB.java:154)
	at com.articulate.sigma.KB.loadEProver(KB.java:3240)
	at com.articulate.sigma.KBmanager.loadKB(KBmanager.java:459)
	at com.articulate.sigma.KBmanager.kbsFromXML(KBmanager.java:365)
	at com.articulate.sigma.KBmanager.setConfiguration(KBmanager.java:673)
	at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:644)
	at com.articulate.sigma.KBmanager.initializeOnce(KBmanager.java:593)
	at com.articulate.sigma.trans.SUMOKBtoTFAKB.initOnce(SUMOKBtoTFAKB.java:36)
	at com.articulate.sigma.trans.SUMOKBtoTFAKB.main(SUMOKBtoTFAKB.java:511)
```

**Comment by arademaker** [comment]
related to #38

**Comment by apease** [comment]
fixed in https://github.com/ontologyportal/sigmakee/commit/63fd424f882321307565de616e4b3b3c2d288e5c - an attempt to do the TFF0 conversion was occurring before kb Cache building was done
